[app]
  port = 1205
  debug = true
  page = 1
  pageSize = 10

[mysql]
  user = "root"
  password = "rootroot"
  host = "127.0.0.1:3306"
  name = "test"

[mongo]
  host = "127.0.0.1:27017"
  user = "echo"
  password = "echo"

[redis]
  user = "root"
  password = "rootroot"
  host = "127.0.0.1:6379"

[auth]
  salt = "salt"
  secret = "token-secret"